# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058d06b469fb17ffb13adb8bde44fad22d47407811f3836abaa380aecf47c3dd7b7d334291771d9939af13c2c8547dc2d4d840686d4674d71f19299d1f14a5da

test:
  secret_key_base: 2bbaf1e54fca583dff3656c89a4ec94a635fcc85371962441fe296db432a4d2f2ab7dc7794b17a18fe99fe137d22ce2c129127ed1438f9c695e7c770b4a76c4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
